### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by Tylersuard** [facebookresearch/music-translation#10]
Can you make a version of the instructions that works for Google Colab?
For instance, the instructions say we need to download the dataset into musicnet folder.  There is no musicnet folder in the repo, where do we create the folder?

You give a link for pretrained models, where do we put them?
Thank you

**Comment by adampolyak** [comment]
Hi, thank you for your interest in our work.

All the paths described in the instructions are from the project root (the directory created by the git clone operation).

The musicnet folder should be created upon the download and unzipping of the musicnet dataset. 

The pretrained models should be saved under the ```checkpoints``` folder. Create it if it doesn't exist.

**Comment by Tylersuard** [comment]
Thank you for your help!  I am now getting this error though: Namespace(input=PosixPath('musicnet'), output=PosixPath('musicnet/parsed'))
Total time for Beethoven with Accompanied Violin is: 8863 seconds
Traceback (most recent call last):
  File "src/parse_musicnet.py", line 84, in <module>
    main()
  File "src/parse_musicnet.py", line 80, in main
    copy(str(fname), str(domaindir))
  File "/usr/lib/python3.6/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'musicnet/musicnet/test_data/2330.wav'

**Comment by Tylersuard** [comment]
This error happens when I run the command listed on the github repo: 
!python src/parse_musicnet.py -i musicnet -o musicnet/parsed
