### ISSUE TITLE
Assertion error: no checkpoints found

### ISSUE THREAD

**Issue by Tylersuard** [facebookresearch/music-translation#12]
checkpoints are in the correct folder, as directed: /content/music-translation/checkpoints/pretrained_musicnet/

`
Starting
<generator object Path.glob at 0x7f4e20704150>

---------------------------------------------------------------------------

AssertionError                            Traceback (most recent call last)

When using generate.ipynb with Colab:

<ipython-input-58-0b2ab91948df> in <module>()
      5 print(checkpoints)
      6 checkpoints = [c for c in checkpoints if extract_id(c) in decoders]
----> 7 assert len(checkpoints) >= 1, "No checkpoints found."
      8 
      9 model_args = torch.load(checkpoint.parent / 'args.pth')[0]

AssertionError: No checkpoints found.

'

**Comment by adampolyak** [comment]
You can manually fix the checkpoint path or change the current working directory to be ```notebooks```. Note that the checkpoint search path is relative to the current working directory.
