### ISSUE TITLE
Finetuning with on new data

### ISSUE THREAD

**Issue by shenkev** [facebookresearch/music-translation#6]
Do you expect it would be possible to finetuning on new genres of music? How much memory does the model consume during training?

**Comment by adampolyak** [comment]
The model was trained on a V100 GPU with 16GB of memory.

In order to add a domain, I would keep the encoder fixed (no need for joint training with a discriminator) and train **only** a new decoder for the new genre. Finetuning a pretrained decoder is also an option.
