### ISSUE TITLE
some doubts about NCC and DTW

### ISSUE THREAD

**Issue by Sycamoretree** [facebookresearch/music-translation#9]
**your aprroach about evaluating:**
Then, we compared the input pitch to the output pitch using either the normalized cross correlation (NCC) obtained for the optimal shift, or Dynamic Time Warping (DTW) followed by a normalized correlation. 
**qusestion 1:**
I am not sure how do you get NCC corretion, if you just compute the Pearson coefficient  between input pitch picture and  the output ,and the result you show is the best.
**question 2:**
Dynamic Time Warping (DTW) followed by a normalized correlation. I saw your resutts are normalized correlation, but the output of dtw with two pictures are distance ,cost matrix and so on ,so  I dont know how to compute a normalized correlation after dtw.

your work is so great,thanks for your help!

**Comment by adampolyak** [comment]
Hi,
Thank you for your interest in our work.
The NCC and DTW metrics were computed versus samples that were created by humans. As a result, the output of our model had a different length than the human created samples.
Therefore, we explored 2 methods to solve this issue:

**question 1:**
I'm not sure I fully understand your question. By shifting the sequence and reporting the NCC for the optimal result. For correlation, we used numpy. correlate

**question 2:**
DTW is required when 2 pitch sequences aren't aligned - for example a scenario where one sequence is shorter than the other. In our work, we used [librosa.sequence.dtw](https://librosa.github.io/librosa/generated/librosa.sequence.dtw.html#librosa.sequence.dtw), to extract the cost matrix and the warping path. 
Using the warping path we strech/squeeze the pitch sequence to match the target sequence length. Then we apply NCC.

I'm closing this issue, feel free to reopen.
